=== cashtotalszero/Unity_tools/psmlXSD/psml.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

   <!-- Definition of <Marker> tag -->
  <xs:complexType name="marker">

    <!-- Nested elements (none at present) -->
    <xs:sequence>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:any minOccurs="0" processContents="skip"/>
      </xs:choice>
    </xs:sequence>

    <!-- Attribute definitions -->
    <xs:attribute name="Width" type="xs:float" use="required"/>
    <xs:attribute name="Height" type="xs:float" use="required"/>
    <xs:attribute name="Graphic" type="xs:string" use="required"/>

  </xs:complexType>

  <!-- Definition of <Connector> tag -->
  <xs:complexType name="connector">

    <!-- Nested elements -->
    <xs:sequence>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element name="Marker" type="marker" minOccurs="0"/>
        <xs:any minOccurs="0" processContents="skip"/>
      </xs:choice>
    </xs:sequence>

    <!-- Attribute definitions -->
     <xs:attribute name="Type" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:enumeration value="Start"/>
          <xs:enumeration value="Stop"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>

    <xs:attribute name="X" type="xs:float" use="required"/>
    <xs:attribute name="Y" type="xs:float" use="required"/>
    <xs:attribute name="Width" type="xs:float" use="required"/>
    <xs:attribute name="Height" type="xs:float" use="required"/>

  </xs:complexType>

  <!-- Definition of <Line> tag -->
  <xs:complexType name="line">

    <!-- Nested elements (none at present) -->
    <xs:sequence>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:any minOccurs="0" processContents="skip"/>
      </xs:choice>
    </xs:sequence>

    <!-- Attribute definitions -->
    <xs:attribute name="Colour" use="optional">
      <xs:simpleType>
        <xs:restriction base="xs:string">
         <xs:pattern value="[#][a-fA-F0-9][a-fA-F0-9][a-fA-F0-9][a-fA-F0-9][a-fA-F0-9][a-fA-F0-9]"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>

    <xs:attribute name="WidthPerLayer" type="xs:float" use="required"/>
    <xs:attribute name="MaxWidth" type="xs:float" use="required"/>
    <xs:attribute name="AvoidJellyfish" type="xs:boolean" use="required"/>
    <xs:attribute name="MergeLinesAtSameLevel" type="xs:boolean" use="required"/>

  </xs:complexType>

  <!-- Definition of <Font> tag -->
  <xs:complexType name="font">

    <!-- Nested elements (none at present) -->
    <xs:sequence>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:any minOccurs="0" processContents="skip"/>
      </xs:choice>
    </xs:sequence>

    <!-- Attribute definitions -->
    <xs:attribute name="Face" use="optional">
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:enumeration value="Arial"/>
          <xs:enumeration value="Times"/>
          <xs:enumeration value="Calibri"/>
          <xs:enumeration value="Impact"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>

    <xs:attribute name="Weight" use="optional">
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:enumeration value="Normal"/>
          <xs:enumeration value="Bold"/>
          <xs:enumeration value="Italic"/>
          <xs:enumeration value="Underline"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>

    <xs:attribute name="Size" type="xs:float" use="optional"/>

    <xs:attribute name="Colour" use="optional">
      <xs:simpleType>
        <xs:restriction base="xs:string">
         <xs:pattern value="[#][a-fA-F0-9][a-fA-F0-9][a-fA-F0-9][a-fA-F0-9][a-fA-F0-9][a-fA-F0-9]"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>

  </xs:complexType>

  <!-- Definition of <Graphic> tag -->
  <xs:complexType name="graphic">

    <!-- Nested elements (none at present) -->
    <xs:sequence>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:any minOccurs="0" processContents="skip"/>
      </xs:choice>
    </xs:sequence>

    <!-- Attribute definitions -->
    <xs:attribute name="Default" type="xs:string" use="required"/>
    <xs:attribute name="Ratio_50" type="xs:string" use="optional"/>
    <xs:attribute name="Ratio_150" type="xs:string" use="optional"/>
    <xs:attribute name="Hover" type="xs:string" use="optional"/>
    <xs:attribute name="Selected" type="xs:string" use="optional"/>
    <xs:attribute name="Disabled" type="xs:string" use="optional"/>

  </xs:complexType>

  <!-- Definition of <HotArea> tag -->
  <xs:complexType name="hotarea">

    <!-- Nested elements (none at present) -->
    <xs:sequence>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:any minOccurs="0" processContents="skip"/>
     </xs:choice>
    </xs:sequence>
  
    <!-- Attribute definitions -->
    <xs:attribute name="X" type="xs:float" use="required"/>
    <xs:attribute name="Y" type="xs:float" use="required"/>
    <xs:attribute name="Width" type="xs:float" use="required"/>
    <xs:attribute name="Height" type="xs:float" use="required"/>

  </xs:complexType>

  <!-- Definition of <BlackHole> tag -->
  <xs:complexType name="blackhole">

    <!-- Nested elements -->
     <xs:sequence>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element name="Graphic" type="graphic" minOccurs="0"/>
        <xs:element name="HotArea" type="hotarea" minOccurs="0"/>
        <xs:any minOccurs="0" processContents="skip"/>
     </xs:choice>
    </xs:sequence>
     
    <!-- Attribute definitions -->
    <xs:attribute name="X" type="xs:float" use="required"/>
    <xs:attribute name="Y" type="xs:float" use="required"/>
    <xs:attribute name="Width" type="xs:float" use="required"/>
    <xs:attribute name="Height" type="xs:float" use="required"/>

  </xs:complexType>
  
  <!-- Definition of <Resize> tag -->
  <xs:complexType name="resize">

    <!-- Nested elements -->
     <xs:sequence>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element name="Graphic" type="graphic" minOccurs="0"/>
        <xs:element name="HotArea" type="hotarea" minOccurs="0"/>
        <xs:any minOccurs="0" processContents="skip"/>
     </xs:choice>
    </xs:sequence>

    <!-- Attribute definitions -->
    <xs:attribute name="MaxX" type="xs:float" use="required"/>
    <xs:attribute name="MaxY" type="xs:float" use="required"/>
    <xs:attribute name="Width" type="xs:float" use="required"/>
    <xs:attribute name="Height" type="xs:float" use="required"/>

  </xs:complexType>

  <!-- Definition of <Title> tag -->
   <xs:complexType name="title">

    <!-- Nested elements -->
     <xs:sequence>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element name="Font" type="font" minOccurs="0"/>
        <xs:any minOccurs="0" processContents="skip"/>
     </xs:choice>
    </xs:sequence>
   
    <!-- Attribute definitions -->
    <xs:attribute name="X" type="xs:float" use="required"/>
    <xs:attribute name="Y" type="xs:float" use="required"/>
    <xs:attribute name="Width" type="xs:float" use="required"/>
    <xs:attribute name="Height" type="xs:float" use="required"/>

    <xs:attribute name="Style" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:enumeration value="Text"/>
          <xs:enumeration value="Graphic"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>

    <xs:attribute name="HorizontalAlignment" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:enumeration value="Centre"/>
          <xs:enumeration value="Left"/>
          <xs:enumeration value="Right"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>

    <xs:attribute name="VerticalAlignment" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:enumeration value="Centre"/>
          <xs:enumeration value="Top"/>
          <xs:enumeration value="Bottom"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>

  </xs:complexType>

  <!-- Definition of <Bungee> tag -->
   <xs:complexType name="bungee">

    <!-- Nested elements -->
     <xs:sequence>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element name="Connector" type="connector" minOccurs="0"/>
        <xs:element name="Line" type = "line" minOccurs="0"/>
        <xs:any minOccurs="0" processContents="skip"/>
     </xs:choice>
    </xs:sequence>

    <!-- Attribute definitions -->
    <!-- NONE -->

  </xs:complexType>

  <!-- Definition of <Style> tag -->
  <xs:complexType name="style">

    <!-- Nested elements -->
    <xs:sequence>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element name="Graphic" type="graphic" minOccurs="0"/>
        <xs:any minOccurs="0" processContents="skip"/>
     </xs:choice>
    </xs:sequence>

    <!-- Attribute definitions -->
    <xs:attribute name="Border" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:enumeration value="Solid"/>
          <xs:enumeration value="Dotted"/>
          <xs:enumeration value="Bold"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    
    <xs:attribute name="FillColour" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:string">
         <xs:pattern value="[#][a-fA-F0-9][a-fA-F0-9][a-fA-F0-9][a-fA-F0-9][a-fA-F0-9][a-fA-F0-9]"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>

  </xs:complexType>
  
  <!-- Definition of <Appearance> tag -->
  <xs:complexType name="appearance">
    
    <!-- Nested elements -->
    <xs:sequence>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element name="Style" type="style" minOccurs="0"/>
        <xs:element name="BlackHole" type="blackhole" minOccurs="0"/>
        <xs:element name="Resize" type="resize" minOccurs="0"/>
        <xs:element name="Title" type="title" minOccurs="0"/>
        <xs:element name="Bungee" type="bungee" minOccurs="0"/>
	<xs:any minOccurs="0" processContents="skip"/>
     </xs:choice>
    </xs:sequence>
  
    <!-- Attribute definitions -->
    <xs:attribute name="Status" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:enumeration value="Default"/>
          <xs:enumeration value="Selected"/>
          <xs:enumeration value="Alert"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    
    <xs:attribute name="AspectRatio" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:float">
         <xs:minInclusive value="0.25"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    
    <xs:attribute name="Spacing" type="xs:float" use="required"/>
    <xs:attribute name="Mask" type="xs:string" use="required"/>
 
  </xs:complexType>

  <!-- Definition of <Jellyfish> tag -->
  <xs:complexType name="jellyfish">
    
    <!-- Nested elements -->
    <xs:sequence>
     <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element name="Appearance" type="appearance" minOccurs="1"/>
        <xs:any minOccurs="0" processContents="skip"/>
     </xs:choice>
    </xs:sequence>
    
    <!-- Attribute definitions -->
    <xs:attribute name="Name" type="xs:string" use="required"/>
   
    <xs:attribute name="Type" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:enumeration value="Static"/>
          <xs:enumeration value="Frozen"/>
          <xs:enumeration value="Floating"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    
    <xs:attribute name="Resizable" type="xs:boolean" use="required"/>  
    <xs:attribute name="LockAspectRatioOnResize" type="xs:boolean" use="optional"/>
  
  </xs:complexType>

  <!-- Definition of <psml> tag -->
  <xs:complexType name="psmltype">
    
    <!-- Nested element <Jellyfish> must occur at least once -->
    <xs:sequence>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element name="Jellyfish" type="jellyfish" minOccurs="1"/>
        <xs:any minOccurs="0" processContents="skip"/>
     </xs:choice>
    </xs:sequence>
    
    <!-- Optional version attribute -->
    <xs:attribute name="Version" type="xs:string" use="optional"/>
 
  </xs:complexType>

  <!-- Declaration of root <psml> element -->
  <xs:element name="psml" type="psmltype"/>

</xs:schema>

=== cashtotalszero/Unity_tools/FINAL/Assets/Scripts/psml.xml
<?xml version="1.0" encoding="UTF-8"?>

<psml Version="889923"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="psml.xsd">
    
    <Jellyfish
        Name="PS1X1"
        Type="Static"
        Resizable="false">
        
        <Appearance
            Status="Default"
            AspectRatio="1.0"
            Spacing="5"
            Mask="Rectangle.svg">
            
            <Style
                Border="Solid"
                FillColour="#660000">
                <Graphic
                    Default="BorderSolid100.svg"
                    Ratio_50="BorderSolid50.svg"
                    Ratio_150="BorderSolid150.svg" />
            </Style>
            
            <BlackHole
                X="88.15" Y="2.75"
                Width="9.1" Height="9.1">
                
                <Graphic
                    Default="BlackHole.svg"
                    Hover="BlackHoleHover.svg"
                    Selected="BlackHoleSelected.svg"
                    Disabled="BlackHoleDisabled.svg" />
              
                
                <HotArea
                    X="85.4" Y="0"
                    Width="14.6" Height="14.6" />
             
            </BlackHole>
            
            <Resize
                MaxX="-9.1" MaxY="-9.1"
                Width="9.1" Height="9.1">
                <Graphic
                    Default="Resize.svg"
                    Hover="ResizeHover.svg"
                    Selected="ResizeSelected.svg"
                    Disabled="ResizeDisabled.svg" />
            
                
                <HotArea
                    X="-14.6"
                    Y="0"
                    Width="14.6" Height="14.6" />
          
                
            </Resize>
            
            <Title
                X="10" Y="0"
                Width="80" Height="15.6"
                Style="Text"
                HorizontalAlignment="Centre"
                VerticalAlignment="Centre">
                <Font
                    Face="Times" Weight="Normal"
                    Size="10" Colour="#BBE9FF" />
            
            </Title>
            
            <Bungee>
                <Connector
                    Type="Start"
                    X="100" Y="93"
                    Width="1.5" Height="7" />
               
                <Connector
                    Type="Stop"
                    X="2"
                    Y="6.3"
                    Width="2"
                    Height="3">
                    <Marker
                        Width="1.5" Height="3"
                        Graphic="MarkerStop.svg" />
                </Connector>
                
                <Line
                    Colour="#BBE9FF"
                    MaxWidth="1.5"
                    WidthPerLayer="0.5"
                    AvoidJellyfish="false"
                    MergeLinesAtSameLevel="true" />
            </Bungee>
            
        </Appearance>
        
    </Jellyfish>
    
    
</psml>

=== cashtotalszero/Unity_tools/psmlXSD/psml.xml
<?xml version="1.0" encoding="UTF-8"?>

<psml Version="889923"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="psml.xsd">

 <Jellyfish 
	Type="Static"
        Name="Alex"
	Resizeable="true">
    <Appearance
	Status="Alert"
	AspectRatio="0.25"
	Spacing="5"
	Mask="Rectangle.svg">
	
       <BlackHole/>
	<Style
		Border="Solid"
		FillColour="#11FA12">
		<Graphic
			Default="whatever.svg"/>
	</Style>
	 
	<Resize/>
	<Title/>
	<Bungee/>

    </Appearance>
 
  </Jellyfish>

</psml>
